services:
  db:
    image: postgres:15-alpine
    container_name: student-bot-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: phe
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d phe"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    networks:
      - student-bot-network

  bot:
    build: .
    container_name: student-bot-app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8080:8080" # Порт для backend.py
    restart: unless-stopped
    networks:
      - student-bot-network
    # CMD из Dockerfile запустит оба скрипта

volumes:
  dbdata:

networks:
  student-bot-network:
    driver: bridge
